# Generated by Django 2.0.3 on 2018-08-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='uploaded_at',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
