# Generated by Django 2.0.3 on 2018-08-30 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20180830_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurtaRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=25)),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurta_colour', to='shopping.Colour')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurta_size', to='shopping.KurtaSize')),
            ],
        ),
    ]
