# Generated by Django 2.0.3 on 2018-08-30 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_kurtarate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurtarate',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='kurtarate',
            name='size',
        ),
        migrations.DeleteModel(
            name='KurtaRate',
        ),
    ]
