# Generated by Django 2.0.3 on 2018-08-30 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_auto_20180830_0813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colour',
        ),
    ]
