# Generated by Django 2.0.3 on 2018-08-30 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurtaRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kurta_color', to='shopping.Color')),
                ('image', models.ManyToManyField(null=True, related_name='kurta_image', to='shopping.Document')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurta_size', to='shopping.KurtaSize')),
            ],
        ),
    ]
