# Generated by Django 2.0.3 on 2018-08-30 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_auto_20180830_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='SareeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=25)),
                ('size', models.CharField(default='Free Size', max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saree_color', to='shopping.Color')),
                ('image', models.ManyToManyField(related_name='saree_image', to='shopping.Document')),
            ],
        ),
        migrations.CreateModel(
            name='TopRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_color', to='shopping.Color')),
                ('image', models.ManyToManyField(related_name='top_image', to='shopping.Document')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_size', to='shopping.TopSize')),
            ],
        ),
        migrations.CreateModel(
            name='TrouserRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=25)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trouser_color', to='shopping.Color')),
                ('image', models.ManyToManyField(related_name='trouser_image', to='shopping.Document')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouser_size', to='shopping.TrouserSize')),
            ],
        ),
    ]
