# Generated by Django 2.0.3 on 2018-08-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_sareerate_toprate_trouserrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SareeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default='Free Size', max_length=25, unique=True)),
            ],
        ),
    ]
