# Generated by Django 2.0.3 on 2018-08-30 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0011_sareesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sareerate',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saree_size', to='shopping.SareeSize'),
        ),
    ]
