# Generated by Django 2.0.3 on 2018-08-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_auto_20180831_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sareerate',
            name='size',
        ),
        migrations.AddField(
            model_name='sareerate',
            name='size',
            field=models.ManyToManyField(related_name='saree_size', to='shopping.KurtaSize'),
        ),
        migrations.RemoveField(
            model_name='toprate',
            name='size',
        ),
        migrations.AddField(
            model_name='toprate',
            name='size',
            field=models.ManyToManyField(related_name='top_size', to='shopping.KurtaSize'),
        ),
        migrations.RemoveField(
            model_name='trouserrate',
            name='size',
        ),
        migrations.AddField(
            model_name='trouserrate',
            name='size',
            field=models.ManyToManyField(related_name='trouser_size', to='shopping.KurtaSize'),
        ),
    ]
