# Generated by Django 2.0.3 on 2018-09-01 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0017_auto_20180831_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dresstype', models.CharField(max_length=25)),
                ('dresspk', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dress_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlacedOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'new'), (1, 'in_progress'), (2, 'delivered')], default=0)),
                ('order', models.ManyToManyField(related_name='ordered_dress', to='shopping.DressOrder')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
