# Generated by Django 2.0.3 on 2018-09-01 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0019_deliveryaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='deliveryaddress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='shopping.DeliveryAddress'),
        ),
    ]
