# Generated by Django 2.0.3 on 2018-09-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_placedorder_deliveryaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dressorder',
            name='paid',
        ),
    ]
