# Generated by Django 2.0.3 on 2018-09-01 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0023_dressorder_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
