# Generated by Django 2.0.3 on 2018-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0026_auto_20180901_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedorder',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
