# Generated by Django 2.0.3 on 2018-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0027_placedorder_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
