# Generated by Django 2.0.3 on 2018-09-01 19:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0030_auto_20180901_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
