# Generated by Django 2.0.3 on 2018-09-01 19:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0033_auto_20180901_1906'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinput',
            unique_together={('user', 'dresspk')},
        ),
    ]
