# Generated by Django 2.0.3 on 2018-09-02 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0035_userinput_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='datetime',
        ),
    ]
