# Generated by Django 2.0.3 on 2018-09-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0037_auto_20180902_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='dresstype',
            field=models.CharField(max_length=25),
        ),
    ]
