# Generated by Django 2.0.3 on 2018-10-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0038_auto_20180902_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
