# Generated by Django 2.0.3 on 2018-10-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0040_auto_20181009_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedorder',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('out_for_delivery', 'out_for_delivery'), ('delivered', 'delivered')], default='new', max_length=25),
        ),
    ]
