# Generated by Django 2.0.3 on 2018-10-09 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0041_auto_20181009_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='placedorder',
            name='deliveryaddress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_address', to='shopping.DeliveryAddress'),
        ),
    ]
